name       : libsigsegv
version    : 2.10
release    : 1
homepage   : https://www.gnu.org/software/libsigsegv/
source     :
    - http://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz : 8460a4a3dd4954c3d96d7a4f5dd5bc4d9b76f5754196aa245287553b26d2199a
license    : GPL-2.0
summary    : GNU libsigsegv is a library for handling page faults in user mode.
description: |
    GNU libsigsegv is a library for handling page faults in user mode. 
    A page fault occurs when a program tries to access to a region of memory that is currently not available.
setup      : |
    %configure --enable-shared --disable-static
build      : |
    %make
install    : |
    %make_install
